const dataConfig = [
  { id: 1, name: '杭州' },
  { id: 2, name: '上海' },
  { id: 5, name: '深圳' },
  { id: 6, name: '南京' },
  { id: 3, name: '北京' },
  { id: 4, name: '广州' },
  { id: 8, name: '天津' },
  { id: 242, name: '成都' },
  { id: 84, name: '苏州' },
  { id: 241, name: '重庆' },
  { id: 175, name: '武汉' },
  { id: 96, name: '嘉兴' },
  { id: 81, name: '无锡' },
  { id: 104, name: '合肥' },
  { id: 141, name: '济南' },
  { id: 120, name: '宣城' },
  { id: 18, name: '廊坊' },
  { id: 219, name: '东莞' },
  { id: 125, name: '泉州' },
  { id: 94, name: '宁波' },
  { id: 122, name: '厦门' },
  { id: 189, name: '长沙' },
  { id: 208, name: '佛山' },
  { id: 83, name: '常州' },
];
module.exports = dataConfig;
